# 도커 컴포즈의 버전을 적는다. 현재 최신 버전인 3
version: "3"

services:
  # 우리 서비스의 이름
  app:
    build:
      # 현재 디렉터리에서 실행할 것이다.
      context: .
    ports:
      # 호스트 포트 8000과 이미지 포트 8000을 매핑한다.
      - "8000:8000"
    # 프로젝트에 대한 업데이트를 실시간으로 받을 수 있는 볼륨을 추가한다.
    # 변경이 일어날 때마다 컨테이너에서 파일이 자동으로 업데이트되므로 도커를 다시 시작할 필요가 없다.
    volumes:
      # 프로젝트의 app 폴더와 도커 이미지 내의 app 폴더를 매핑한다.
      - ./app:/app
    # 응용 프로그램을 실행하는데 사용되는 명령을 Docker 컨테이너에 입력한다.
    # 한 줄 이상 적을 때는 > 심볼을 이용하고 그 다음줄부터 들여쓰기해서 적으면 된다.
    # sh -c 는 command를 shell에서 실행한다는 뜻이다.
    # 서버를 실행할 호스트의 주소가 0.0.0.0:8000이다. 즉, 실행되는 모든 IP 주소에서 사용할 수 있는 Django 개발 서버가 실행된다.
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
